/*
 * Author: dixon13 aka D.Begay 71st Special Operations Group
 * Date: May 2, 2015
 * Release: Version 1.0
 * Description: set of functions and macros that makes a unit a hostage and releases them from captivity
 *
*/

/*------------------------ DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING ------------------------------*/
#define Q(var) #var
#define CALL_COMPILE(var) call compileFinal preprocessFileLineNumbers Q(var)
#define PV(var) publicVariable Q(var)
#define setVar(var1,var2,var3) setVariable[var1,var2,var3]
#define getVar(var1,var2) getVariable[var1,var2]
#define PARAM(var,var1,var2) [_this,var,var1,var2] call BIS_fnc_param
//#define debug true

XON_fnc_MPaddAction = {
	private[Q(_object),Q(_arg),Q(_actionID)];
	_object = PARAM(0,objNull,[objNull]);
	_arg = _this select 1;//type {}
	
	_actionID = _object addAction _arg;
	_object setVar(Q(actionID),_actionID,true);
	_actionID;
};

XON_fnc_MPremoveAction = {
	private[Q(_object)];
	_object = PARAM(0,objNull,[objNull]);
	
	_actionID = _object getVar(Q(actionID),0);
	_object removeAction _actionID;
	true;
};

XON_fnc_detain = {
	private[Q(_object),Q(_unit)];
	_object = PARAM(0,objNull,[objNull]);
	_unit = PARAM(1,objNull,[objNull]);

	_object switchMove Q(AmovPercMstpSsurWnonDnon_AmovPercMstpSnonWnonDnon);
	_object enableAI Q(MOVE);
	group _object setCombatMode Q(BLUE);
	_object setUnitPos Q(AUTO);
	[_object] joinSilent (group _unit);
	diag_log format[Q(XON_fnc_setCaptive - removing action from %1),_object];
	[[_object],Q(XON_fnc_MPremoveAction),true,true] call BIS_fnc_MP;;
};

XON_fnc_setCaptive = {
	private[Q(_unit),Q(_targetObj)];
	_unit = PARAM(0,objNull,[objNull]);
	_targetObj = _this select 1; //Object, Array of objects, Boolean, Number, Side, Group
	
	_unit playMove Q(amovpercmstpsnonwnondnon_amovpercmstpssurwnondnon);
	_unit setCaptive true;
	_unit disableAI Q(MOVE);
	_unit disableAI Q(AUTOTARGET);
	diag_log format[Q(XON_fnc_setCaptive - adding action to %1),_unit];
	[[_unit,[Q(<t color='#ff0000'>Rescue</t>),{ _unit = _this select 3; [_unit, (_this select 1)] call XON_fnc_detain; },_unit,10,false,true,"",Q(((player distance _target) < 3 ))]],Q(XON_fnc_MPaddAction),_targetObj,true] call BIS_fnc_MP;
	true;
};
